# Generated by Django 4.2.5 on 2023-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=250),
        ),
    ]
