version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pg_db
    ports:
      - '5433:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 3 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    tty: true
    command: sh -c "sleep 5 && celery -A config worker -l INFO"
    depends_on:
        - redis
        - app

  celery_beat:
    build: .
    tty: true
    command: sh -c "sleep 10 && celery -A config beat -l info -S django"
    depends_on:
      - celery
      - redis
      - app

