version: '3.11'

services:
  db:
    image: postgres:latest
    environment:
      - .env
      - POSTGRES_HOST_AUTH_METHOD=trust
#      POSTGRES_PASSWORD: mysecretpassword
#      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready']
#      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy