# Generated by Django 4.2.5 on 2023-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_subscription_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сourse',
            name='user',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=450, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='сourse',
            name='description',
            field=models.TextField(blank=True, max_length=450, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='сourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='картинка'),
        ),
    ]
